### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by DonQueso89** [DonQueso89/LBCS#16]
{
    default_color: [int, int, int],
    default_brightness: decimal 0 < x <= 1
}

we can use this expo lib https://docs.expo.io/versions/latest/sdk/async-storage/ for storing simple key value pairs

**Comment by AthulMuralidhar** [comment]
# Things to do here:

- [ ] make the colours in the boulder grid homogenous

this is the only thing that i can remember now haha, feel free to add more stuff here @DonQueso89

**Comment by DonQueso89** [comment]
its not necessarily about making the colors the same. Its just about storing a json somewhere with some config which can later be applied in the component. One of those config is the default_color yes

**Comment by DonQueso89** [comment]
Ive taken this one over
